platform :ios,'7.0'
pod 'ReactiveCocoa'
pod 'AFNetworking', '~> 2.6.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 0.6.3'
pod 'HBKit', :git => 'https://github.com/Natoto/HBFastTableViewCotroller.git',:commit => '8d5a7a5f22638226a0f130985f420f14c0e175d8'
pod 'yytext', :git => 'https://github.com/Natoto/yytextdemo.git'
#注释
